### ISSUE TITLE
Undefined values on RIGHT key for custom primaryTextKey

### ISSUE THREAD

**Issue by paulgoetze** [danqing/autocomplete#1]
Awesome lib, exactly what I was looking for!

I think the `.title` calls in https://github.com/danqing/autocomplete/blob/master/ac.js#L247 and https://github.com/danqing/autocomplete/blob/master/ac.js#L306 should be 

``` js
... this.results[this.selectedIndex][this.primaryTextKey];
```

Else you would get an "undefined" value written into the input on pressing the right key.

**Comment by danqing** [comment]
You are totally right. I think this is now fixed.
